services:
  samsung-scantopc:
    build: .
    platform: linux/amd64
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_BROADCAST
      - NET_RAW
    volumes:
      - ./scans:/scans
    environment:
      SCAN_OPTIONS: >-
        [
          {"name": "Color PDF",  "color": "COLOR_TRUE", "resolution": "DPI_300", "format": "FORMAT_M_PDF", "size": "SIZE_A4"}
        ]
      SCAN_OUTPUT_DIR: "/scans"
      SCAN_FILENAME_TEMPLATE: "SCAN_$${datetime}__$${uid}"
    restart: unless-stopped
